// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGbINgoq48iJKNJB3CnHdqfnhrwSs5k1E',
    appId: '1:171747079923:web:693d87ad91141f73006986',
    messagingSenderId: '171747079923',
    projectId: 'super-operator',
    authDomain: 'super-operator.firebaseapp.com',
    storageBucket: 'super-operator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUeG07k19-bXpvSrQh3PJlo3ihvqDCz88',
    appId: '1:171747079923:android:25f9ba306139d87c006986',
    messagingSenderId: '171747079923',
    projectId: 'super-operator',
    storageBucket: 'super-operator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6A9q7_5V_JAVjN4biCIIqWGlAr8DiMVU',
    appId: '1:171747079923:ios:cf2e4418f5b716c1006986',
    messagingSenderId: '171747079923',
    projectId: 'super-operator',
    storageBucket: 'super-operator.appspot.com',
    iosBundleId: 'com.example.superOperator',
  );
}
